### ISSUE TITLE
Consultas para visualización de resultados

### ISSUE THREAD

**Issue by dierodfer** [EGC-G2-Trabajo-1718/Visualizacion_Resultados#1]
**Título**: Consultas para visualización de resultados
**Prioridad**: alto
**Estado**: pendiente
**Descripción:** 
Se necesita satisfacer la llamadas a sus respectivas APIs, se generará un json con los datos requeridos:
* Para una encuesta:

1. - [x] Número de participantes máximo del censo X (administración de censos)

2. - [x] Número de votos realizados de una encuesta X (recuento)

* Para una encuesta finalizada:

3. - [x] Lista de respuestas, junto con el numero de votos realizados, de una encuesta X (recuento)
4. - [ ] Lista de edades de todos los participantes de una encuesta finalizada X (recuento)
5. - [ ] Lista de ciudad,provincia,país con el número de participantes de dicha ciudad,provincia,país una encuesta X (recuento)
6. - [ ] Lista de horas de todos los votos de una encuesta X	(recuento)

**Subsistemas involucrados:**
* @EGC-G2-Trabajo-1718/recuento
* @EGC-G2-Trabajo-1718/administracion_censos 

**Etiquetas:** help wanted

**Comment by adrluqmon** [comment]
El tipo .json que solicitamos para realizar una gráfica de edades es el siguiente:

{
  "data": [
    {
      "edad": 79
    },
    {
      "edad": 36
    },
    {
      "edad": 75
    },
    {
      "edad": 73
    },
    {
      "edad": 43
    },
    {
      "edad": 63
    },
    {
      "edad": 34
    },
    {
      "edad": 25
    }
]
}

**Comment by dierodfer** [comment]
**Estructura de datos recibidos:**

_Lista de edades de todos los participantes de una encuesta finalizada X_
El tipo .json que solicitamos para realizar una gráfica de edades es el siguiente:
{
"data": [
{"edad": 79},
{"edad": 36},
{"edad": 75}
}
Entiéndase, por cada voto, la edad del votante.

_Lista de ciudad,provincia,país con el número de participantes de dicha ciudad,provincia,país una encuesta X_
El tipo .json que solicitamos para crear una gráfica basada en las ciudades es el siguiente:
{
  "data": [
    {"huelva": 416},
    {"sevilla": 49 },
    {"cadiz": 100},
    {"cordoba": 211},
    {"jaen": 10},
    {"almeria": 198}
]
}
Entiendase, por cada ciudad a la que pertenezca cada votante, el numero total de votos.

**Comment by dierodfer** [comment]
Issue cerrada movida al repositorio de @EGC-G2-Trabajo-1718/recuento
